-- Campus Pocket Phase-1 schema
-- Idempotent migration for Supabase Postgres

CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
    CREATE TYPE user_role AS ENUM ('parent', 'student');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'attendance_status') THEN
    CREATE TYPE attendance_status AS ENUM ('PRESENT', 'ABSENT', 'LATE');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'fee_status') THEN
    CREATE TYPE fee_status AS ENUM ('PAID', 'PENDING', 'OVERDUE');
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS "user" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role user_role NOT NULL,
  full_name TEXT NOT NULL,
  school_id INTEGER NOT NULL CHECK (school_id > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS parent_student_link (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id BIGINT NOT NULL REFERENCES "user" (id) ON DELETE CASCADE,
  student_id BIGINT NOT NULL REFERENCES "user" (id) ON DELETE CASCADE,
  UNIQUE (parent_id, student_id)
);

CREATE TABLE IF NOT EXISTS classroom (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  school_id INTEGER NOT NULL CHECK (school_id > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS classroom_membership (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classroom_id BIGINT NOT NULL REFERENCES classroom (id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES "user" (id) ON DELETE CASCADE,
  role user_role NOT NULL DEFAULT 'student',
  CHECK (role = 'student'),
  UNIQUE (classroom_id, user_id)
);

CREATE TABLE IF NOT EXISTS class_session (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classroom_id BIGINT NOT NULL REFERENCES classroom (id) ON DELETE CASCADE,
  session_date DATE NOT NULL,
  topic TEXT NOT NULL,
  UNIQUE (classroom_id, session_date)
);

CREATE TABLE IF NOT EXISTS attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL REFERENCES "user" (id) ON DELETE CASCADE,
  session_id BIGINT NOT NULL REFERENCES class_session (id) ON DELETE CASCADE,
  status attendance_status NOT NULL,
  UNIQUE (student_id, session_id)
);

CREATE TABLE IF NOT EXISTS assignment (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classroom_id BIGINT NOT NULL REFERENCES classroom (id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  total_marks INTEGER NOT NULL CHECK (total_marks > 0),
  due_date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS assignment_submission (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assignment_id BIGINT NOT NULL REFERENCES assignment (id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES "user" (id) ON DELETE CASCADE,
  score NUMERIC(6,2) NOT NULL CHECK (score >= 0),
  total INTEGER NOT NULL CHECK (total > 0),
  percentage NUMERIC(5,2)
    GENERATED ALWAYS AS (
      CASE
        WHEN total > 0 THEN ROUND((score / total::NUMERIC) * 100.0, 2)
        ELSE NULL
      END
    ) STORED,
  submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (score <= total),
  UNIQUE (assignment_id, user_id)
);

CREATE TABLE IF NOT EXISTS fees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL REFERENCES "user" (id) ON DELETE CASCADE,
  amount NUMERIC(10,2) NOT NULL CHECK (amount > 0),
  due_date DATE NOT NULL,
  status fee_status NOT NULL,
  paid_on DATE NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (
    (status = 'PAID' AND paid_on IS NOT NULL)
    OR
    (status <> 'PAID')
  )
);

CREATE INDEX IF NOT EXISTS idx_parent_student_link_parent_id ON parent_student_link (parent_id);
CREATE INDEX IF NOT EXISTS idx_parent_student_link_student_id ON parent_student_link (student_id);
CREATE INDEX IF NOT EXISTS idx_classroom_membership_classroom_id ON classroom_membership (classroom_id);
CREATE INDEX IF NOT EXISTS idx_classroom_membership_user_id ON classroom_membership (user_id);
CREATE INDEX IF NOT EXISTS idx_class_session_classroom_id ON class_session (classroom_id);
CREATE INDEX IF NOT EXISTS idx_attendance_student_id ON attendance (student_id);
CREATE INDEX IF NOT EXISTS idx_attendance_session_id ON attendance (session_id);
CREATE INDEX IF NOT EXISTS idx_assignment_classroom_id ON assignment (classroom_id);
CREATE INDEX IF NOT EXISTS idx_assignment_submission_assignment_id ON assignment_submission (assignment_id);
CREATE INDEX IF NOT EXISTS idx_assignment_submission_user_id ON assignment_submission (user_id);
CREATE INDEX IF NOT EXISTS idx_fees_student_id ON fees (student_id);

CREATE OR REPLACE FUNCTION fn_validate_parent_student_link()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  parent_role user_role;
  student_role user_role;
  parent_school INTEGER;
  student_school INTEGER;
BEGIN
  SELECT role, school_id INTO parent_role, parent_school FROM "user" WHERE id = NEW.parent_id;
  SELECT role, school_id INTO student_role, student_school FROM "user" WHERE id = NEW.student_id;

  IF parent_role IS NULL OR student_role IS NULL THEN
    RAISE EXCEPTION 'Parent or student user does not exist';
  END IF;

  IF parent_role <> 'parent' THEN
    RAISE EXCEPTION 'parent_id % is not a parent user', NEW.parent_id;
  END IF;

  IF student_role <> 'student' THEN
    RAISE EXCEPTION 'student_id % is not a student user', NEW.student_id;
  END IF;

  IF parent_school <> student_school THEN
    RAISE EXCEPTION 'Parent and student must belong to the same school';
  END IF;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION fn_validate_classroom_membership()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  user_role_val user_role;
  user_school INTEGER;
  classroom_school INTEGER;
BEGIN
  SELECT role, school_id INTO user_role_val, user_school FROM "user" WHERE id = NEW.user_id;
  SELECT school_id INTO classroom_school FROM classroom WHERE id = NEW.classroom_id;

  IF user_role_val IS NULL OR classroom_school IS NULL THEN
    RAISE EXCEPTION 'User or classroom does not exist';
  END IF;

  IF user_role_val <> 'student' THEN
    RAISE EXCEPTION 'Only student users can join classroom memberships';
  END IF;

  IF NEW.role <> 'student' THEN
    RAISE EXCEPTION 'classroom_membership.role must be student';
  END IF;

  IF user_school <> classroom_school THEN
    RAISE EXCEPTION 'Student and classroom must be from the same school';
  END IF;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION fn_validate_attendance_student_session()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  student_role_val user_role;
  membership_exists BOOLEAN;
BEGIN
  SELECT role INTO student_role_val FROM "user" WHERE id = NEW.student_id;

  IF student_role_val <> 'student' THEN
    RAISE EXCEPTION 'Attendance can only be recorded for student users';
  END IF;

  SELECT EXISTS (
    SELECT 1
    FROM class_session cs
    JOIN classroom_membership cm
      ON cm.classroom_id = cs.classroom_id
     AND cm.user_id = NEW.student_id
     AND cm.role = 'student'
    WHERE cs.id = NEW.session_id
  ) INTO membership_exists;

  IF NOT membership_exists THEN
    RAISE EXCEPTION 'Student % is not a member of the classroom for session %', NEW.student_id, NEW.session_id;
  END IF;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION fn_validate_assignment_submission()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  student_role_val user_role;
  assignment_total INTEGER;
  assignment_classroom BIGINT;
  membership_exists BOOLEAN;
BEGIN
  SELECT role INTO student_role_val FROM "user" WHERE id = NEW.user_id;

  IF student_role_val <> 'student' THEN
    RAISE EXCEPTION 'Only student users can submit assignments';
  END IF;

  SELECT total_marks, classroom_id
    INTO assignment_total, assignment_classroom
    FROM assignment
   WHERE id = NEW.assignment_id;

  IF assignment_total IS NULL THEN
    RAISE EXCEPTION 'Assignment % does not exist', NEW.assignment_id;
  END IF;

  IF NEW.total <> assignment_total THEN
    RAISE EXCEPTION 'Submission total (%) must match assignment total_marks (%)', NEW.total, assignment_total;
  END IF;

  SELECT EXISTS (
    SELECT 1
    FROM classroom_membership cm
    WHERE cm.classroom_id = assignment_classroom
      AND cm.user_id = NEW.user_id
      AND cm.role = 'student'
  ) INTO membership_exists;

  IF NOT membership_exists THEN
    RAISE EXCEPTION 'Student % is not a member of assignment classroom %', NEW.user_id, assignment_classroom;
  END IF;

  RETURN NEW;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_validate_parent_student_link') THEN
    CREATE TRIGGER trg_validate_parent_student_link
    BEFORE INSERT OR UPDATE ON parent_student_link
    FOR EACH ROW
    EXECUTE FUNCTION fn_validate_parent_student_link();
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_validate_classroom_membership') THEN
    CREATE TRIGGER trg_validate_classroom_membership
    BEFORE INSERT OR UPDATE ON classroom_membership
    FOR EACH ROW
    EXECUTE FUNCTION fn_validate_classroom_membership();
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_validate_attendance_student_session') THEN
    CREATE TRIGGER trg_validate_attendance_student_session
    BEFORE INSERT OR UPDATE ON attendance
    FOR EACH ROW
    EXECUTE FUNCTION fn_validate_attendance_student_session();
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_validate_assignment_submission') THEN
    CREATE TRIGGER trg_validate_assignment_submission
    BEFORE INSERT OR UPDATE ON assignment_submission
    FOR EACH ROW
    EXECUTE FUNCTION fn_validate_assignment_submission();
  END IF;
END $$;

CREATE OR REPLACE VIEW student_attendance_summary AS
SELECT
  u.id AS student_id,
  u.full_name AS student_name,
  u.school_id,
  COUNT(a.id) AS total_sessions,
  COUNT(*) FILTER (WHERE a.status = 'PRESENT') AS present_count,
  COUNT(*) FILTER (WHERE a.status = 'LATE') AS late_count,
  COUNT(*) FILTER (WHERE a.status = 'ABSENT') AS absent_count,
  ROUND(
    (
      (COUNT(*) FILTER (WHERE a.status = 'PRESENT')
      + COUNT(*) FILTER (WHERE a.status = 'LATE') * 0.5)::NUMERIC
      /
      NULLIF(COUNT(a.id), 0)
    ) * 100.0,
    2
  ) AS attendance_percentage
FROM "user" u
LEFT JOIN attendance a ON a.student_id = u.id
WHERE u.role = 'student'
GROUP BY u.id, u.full_name, u.school_id;

CREATE OR REPLACE VIEW student_grade_summary AS
SELECT
  u.id AS student_id,
  u.full_name AS student_name,
  u.school_id,
  COUNT(s.id) AS submissions_count,
  ROUND(AVG(s.percentage), 2) AS average_percentage
FROM "user" u
LEFT JOIN assignment_submission s ON s.user_id = u.id
WHERE u.role = 'student'
GROUP BY u.id, u.full_name, u.school_id;

CREATE OR REPLACE VIEW parent_child_overview AS
SELECT
  p.id AS parent_id,
  p.full_name AS parent_name,
  s.id AS student_id,
  s.full_name AS student_name,
  s.school_id,
  att.attendance_percentage,
  grd.average_percentage,
  COALESCE(f.pending_fees_count, 0) AS pending_fees_count,
  COALESCE(f.pending_fees_amount, 0) AS pending_fees_amount
FROM parent_student_link l
JOIN "user" p ON p.id = l.parent_id
JOIN "user" s ON s.id = l.student_id
LEFT JOIN student_attendance_summary att ON att.student_id = s.id
LEFT JOIN student_grade_summary grd ON grd.student_id = s.id
LEFT JOIN (
  SELECT
    student_id,
    COUNT(*) FILTER (WHERE status IN ('PENDING', 'OVERDUE')) AS pending_fees_count,
    COALESCE(SUM(amount) FILTER (WHERE status IN ('PENDING', 'OVERDUE')), 0) AS pending_fees_amount
  FROM fees
  GROUP BY student_id
) f ON f.student_id = s.id;
