-- Phase 4 Parent Portal Expansion

CREATE TYPE announcement_priority AS ENUM ('LOW', 'NORMAL', 'HIGH', 'URGENT');

CREATE TABLE IF NOT EXISTS announcements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id INTEGER NOT NULL CHECK (school_id > 0),
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  type TEXT NOT NULL, -- e.g., 'event', 'alert', 'news'
  priority announcement_priority NOT NULL DEFAULT 'NORMAL',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS holidays (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id INTEGER NOT NULL CHECK (school_id > 0),
  title TEXT NOT NULL,
  date DATE NOT NULL,
  type TEXT NOT NULL -- e.g., 'public', 'school'
);

CREATE TYPE message_status AS ENUM ('UNREAD', 'READ', 'REPLIED');

CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id INTEGER NOT NULL CHECK (school_id > 0),
  parent_id BIGINT NOT NULL REFERENCES "user" (id) ON DELETE CASCADE,
  student_id BIGINT NOT NULL REFERENCES "user" (id) ON DELETE CASCADE,
  teacher_name TEXT NOT NULL,
  subject TEXT NOT NULL,
  message TEXT NOT NULL,
  reply TEXT,
  status message_status NOT NULL DEFAULT 'UNREAD',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  replied_at TIMESTAMPTZ
);

-- Enhance class_session for Timetable
ALTER TABLE class_session 
ADD COLUMN IF NOT EXISTS start_time TIME,
ADD COLUMN IF NOT EXISTS end_time TIME,
ADD COLUMN IF NOT EXISTS room TEXT;

CREATE INDEX IF NOT EXISTS idx_announcements_school_id ON announcements(school_id);
CREATE INDEX IF NOT EXISTS idx_holidays_school_id ON holidays(school_id);
CREATE INDEX IF NOT EXISTS idx_messages_parent_id ON messages(parent_id);

-- Dummy Data for new tables
DO $$
DECLARE
  sid INTEGER := 1;
  pid BIGINT;
  stid BIGINT;
BEGIN
  -- Get first parent and student
  SELECT parent_id, student_id INTO pid, stid FROM parent_student_link LIMIT 1;
  
  IF pid IS NOT NULL THEN
    -- Announcements
    INSERT INTO announcements (school_id, title, message, type, priority) VALUES
    (sid, 'Science Fair Next Week', 'Please encourage your children to participate in the upcoming science fair.', 'event', 'NORMAL'),
    (sid, 'Fees Overdue Warning', 'A reminder to clear any pending dues before the final exams.', 'alert', 'HIGH'),
    (sid, 'School closed tomorrow', 'Due to heavy rain, school will remain closed.', 'news', 'URGENT');

    -- Holidays
    INSERT INTO holidays (school_id, title, date, type) VALUES
    (sid, 'Summer Break Start', CURRENT_DATE + INTERVAL '10 days', 'school'),
    (sid, 'National Holiday', CURRENT_DATE + INTERVAL '15 days', 'public');

    -- Messages
    INSERT INTO messages (school_id, parent_id, student_id, teacher_name, subject, message, reply, status) VALUES
    (sid, pid, stid, 'Mr. Smith', 'Math Performance', 'Your child is doing great in Math.', 'Thank you! Keep up the good work.', 'REPLIED'),
    (sid, pid, stid, 'Mrs. Davis', 'Absence Inquiry', 'Please provide a note for last Tuesday.', NULL, 'UNREAD');

    -- Update class_session dummy data for timetable
    UPDATE class_session SET start_time = '09:00:00', end_time = '09:45:00', room = 'Room 101' WHERE id % 3 = 0;
    UPDATE class_session SET start_time = '10:00:00', end_time = '10:45:00', room = 'Lab 2' WHERE id % 3 = 1;
    UPDATE class_session SET start_time = '11:00:00', end_time = '11:45:00', room = 'Room 105' WHERE id % 3 = 2;
  END IF;
END $$;
