-- Step 1: Create the new timetable table for a weekly schedule
CREATE TABLE IF NOT EXISTS class_timetable (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classroom_id BIGINT NOT NULL REFERENCES classroom(id) ON DELETE CASCADE,
  day_of_week TEXT NOT NULL CHECK (day_of_week IN ('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday')),
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  subject TEXT NOT NULL,
  teacher_name TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_class_timetable_classroom ON class_timetable(classroom_id);

-- Step 2: Seed the timetable for the first classroom
DO $$
DECLARE
  cid BIGINT;
BEGIN
  SELECT id INTO cid FROM classroom LIMIT 1;
  IF cid IS NOT NULL THEN
    -- Monday
    INSERT INTO class_timetable (classroom_id, day_of_week, start_time, end_time, subject, teacher_name) VALUES
    (cid, 'Monday', '09:00:00', '09:45:00', 'Mathematics', 'Mr. Smith'),
    (cid, 'Monday', '09:50:00', '10:35:00', 'Physics', 'Mrs. Davis'),
    (cid, 'Monday', '10:45:00', '11:30:00', 'English', 'Ms. Taylor');

    -- Tuesday
    INSERT INTO class_timetable (classroom_id, day_of_week, start_time, end_time, subject, teacher_name) VALUES
    (cid, 'Tuesday', '09:00:00', '09:45:00', 'Chemistry', 'Mr. Wilson'),
    (cid, 'Tuesday', '09:50:00', '10:35:00', 'Mathematics', 'Mr. Smith');

    -- Wednesday
    INSERT INTO class_timetable (classroom_id, day_of_week, start_time, end_time, subject, teacher_name) VALUES
    (cid, 'Wednesday', '09:00:00', '09:45:00', 'Biology', 'Dr. Adams'),
    (cid, 'Wednesday', '09:50:00', '10:35:00', 'History', 'Mr. Brown');

    -- Thursday
    INSERT INTO class_timetable (classroom_id, day_of_week, start_time, end_time, subject, teacher_name) VALUES
    (cid, 'Thursday', '09:00:00', '09:45:00', 'Physics', 'Mrs. Davis'),
    (cid, 'Thursday', '09:50:00', '10:35:00', 'Computer Science', 'Ms. Clark');

    -- Friday
    INSERT INTO class_timetable (classroom_id, day_of_week, start_time, end_time, subject, teacher_name) VALUES
    (cid, 'Friday', '09:00:00', '09:45:00', 'English', 'Ms. Taylor'),
    (cid, 'Friday', '09:50:00', '10:35:00', 'Physical Education', 'Coach Carter');

    -- Saturday
    INSERT INTO class_timetable (classroom_id, day_of_week, start_time, end_time, subject, teacher_name) VALUES
    (cid, 'Saturday', '09:00:00', '11:00:00', 'Extracurricular / Club', 'Various');
  END IF;
END $$;

-- Step 3: Seed Indian Holidays
DO $$
DECLARE
  sid INTEGER := 1;
BEGIN
  -- Clear existing dummy holidays to avoid duplicates
  DELETE FROM holidays WHERE school_id = sid;

  -- Insert Indian Holidays
  INSERT INTO holidays (school_id, title, date, type) VALUES
  (sid, 'Republic Day', '2026-01-26', 'public'),
  (sid, 'Holi', '2026-03-03', 'public'),
  (sid, 'Good Friday', '2026-04-03', 'public'),
  (sid, 'Eid al-Fitr', '2026-03-20', 'public'),
  (sid, 'Independence Day', '2026-08-15', 'public'),
  (sid, 'Gandhi Jayanti', '2026-10-02', 'public'),
  (sid, 'Dussehra', '2026-10-19', 'public'),
  (sid, 'Diwali', '2026-11-08', 'public'),
  (sid, 'Christmas', '2026-12-25', 'public'),
  (sid, 'Summer Vacation', '2026-05-15', 'school'),
  (sid, 'Winter Break', '2026-12-26', 'school');
END $$;
