-- 006_student_portal_expansion.sql
-- Creates badges table and rules table

CREATE TABLE IF NOT EXISTS student_badges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE,
    student_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(100) NOT NULL,
    category VARCHAR(50) NOT NULL,
    description TEXT NOT NULL,
    icon VARCHAR(50),
    earned_at TIMESTAMPTZ DEFAULT NOW(),
    rarity VARCHAR(20) DEFAULT 'Common'
);

ALTER TABLE student_badges ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own badges"
ON student_badges FOR SELECT
TO authenticated
USING (student_id = auth.uid());

CREATE POLICY "Admins can manage badges"
ON student_badges FOR ALL
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM users
    WHERE users.id = auth.uid()
      AND users.role = 'admin'
      AND users.school_id = student_badges.school_id
  )
);

CREATE INDEX idx_student_badges_student_id ON student_badges(student_id);
