-- Step 1: Create notification_preferences table
CREATE TABLE IF NOT EXISTS notification_preferences (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  exams_enabled BOOLEAN DEFAULT true,
  fees_enabled BOOLEAN DEFAULT true,
  assignments_enabled BOOLEAN DEFAULT true,
  announcements_enabled BOOLEAN DEFAULT true
);

-- Step 2: Create notifications table
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('parent', 'student')),
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  type TEXT NOT NULL,
  priority TEXT NOT NULL CHECK (priority IN ('high', 'medium', 'low')),
  is_read BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  redirect_route TEXT
);

-- Turn on realtime for notifications
alter table notifications replica identity full;

-- Step 3: Seed mock data for notifications
DO $$
DECLARE
  student_user_id UUID;
  parent_user_id UUID;
BEGIN
  -- Get first student and parent
  SELECT u.id INTO student_user_id FROM auth.users u JOIN user_roles ur ON u.id = ur.user_id WHERE ur.role = 'student' LIMIT 1;
  SELECT u.id INTO parent_user_id FROM auth.users u JOIN user_roles ur ON u.id = ur.user_id WHERE ur.role = 'parent' LIMIT 1;

  IF student_user_id IS NOT NULL THEN
    INSERT INTO notification_preferences (user_id) VALUES (student_user_id) ON CONFLICT DO NOTHING;
    INSERT INTO notifications (user_id, role, title, message, type, priority, is_read, redirect_route) VALUES
    (student_user_id, 'student', 'Assignment Due', 'Science assignment is due tomorrow. Please submit on time.', 'assignment', 'high', false, '/student/assignments'),
    (student_user_id, 'student', 'Exam Reminder', 'Quarterly exam starts Monday. Ensure you have downloaded the syllabus.', 'exam', 'high', false, '/student/report-card'),
    (student_user_id, 'student', 'Homework Pending', 'You have pending homework in English.', 'homework', 'medium', true, '/student/assignments'),
    (student_user_id, 'student', 'Timetable Updated', 'A new timetable has been published for next week.', 'timetable', 'low', false, '/student/timetable');
  END IF;

  IF parent_user_id IS NOT NULL THEN
    INSERT INTO notification_preferences (user_id) VALUES (parent_user_id) ON CONFLICT DO NOTHING;
    INSERT INTO notifications (user_id, role, title, message, type, priority, is_read, redirect_route) VALUES
    (parent_user_id, 'parent', 'Exam Alert', 'Math Final Exam starts in 3 days.', 'exam', 'high', false, '/parent/report-card'),
    (parent_user_id, 'parent', 'Fee Reminder', 'Fee payment is pending for April.', 'fee', 'high', false, '/parent/fees'),
    (parent_user_id, 'parent', 'Attendance Warning', 'Attendance dropped to 72%. Please review.', 'attendance', 'high', false, '/parent/attendance'),
    (parent_user_id, 'parent', 'Report Card Published', 'New report card uploaded for the recent Quarterly Exam.', 'report', 'medium', true, '/parent/report-card');
  END IF;
END $$;
